#!/bin/sh /etc/rc.common
START=99

printMsg() {
    local msg="$1"
    logger -t "${PROGRAM}" "${msg}"
}

start(){
  # 禁用内核热管理对风扇的自动控制
  echo disabled > /sys/class/thermal/thermal_zone0/mode 2>/dev/null
  /usr/bin/fancts.sh &
  printMsg "Airpi风扇控制模块开始工作！"
  cp /usr/bin/footer.htm /usr/lib/lua/luci/view/themes/argon/footer.htm 2>/dev/null
  cp /usr/bin/wps /etc/rc.button/wps 2>/dev/null
}

stop(){
  killall fancts.sh 2>/dev/null
  printMsg "Airpi风扇控制模块已停止！"
}
